spring:
  application:
    name: print3
  datasource:
    url: jdbc:mysql://localhost:3306/criminal_evidence?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
  jpa:
    show-sql: true
    generate-ddl: true